# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('agente', models.CharField(blank=True, max_length=15, null=True)),
                ('ambiente', models.CharField(blank=True, max_length=15, null=True)),
                ('suitedpto', models.CharField(blank=True, max_length=15, null=True)),
                ('reporta', models.CharField(blank=True, max_length=15, null=True)),
                ('areaatencion', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('solucion', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
